name: Sync repository

on:
  schedule:
    - cron: '0 0 * * *'  # This will run at 00:00 UTC every day
  workflow_dispatch:  # This allows the workflow to be manually triggered

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Sync repository
      uses: reposyncer/reposync@v2
      with:
        name: gnu-wget
        url: https://gitlab.com/gnuwget/wget2.git
